const PosTmsStatusCodes = {
    "00": "Transaction Approved",
    "01": "Transaction Approved",
    "03": "No Merchant",
    "04": "Pick Up Card",
    "05": "Do Not Honor",
    "06": "contact their card issuer and/or use an alternate card",
    "08": "Honour with Identification",
    "09": "Request in Progress",
    10: "Approved for Partial Amount",
    12: "Invalid Transaction",
    13: "Invalid Amount",
    14: "Invalid Card Number",
    15: "No Issuer",
    19: "Re-Enter Last Transaction",
    21: "No Action Taken",
    22: "Suspected Malfunction",
    23: "Unacceptable Transaction Fee",
    25: "Unable to Locate Record on File",
    30: "Format Error",
    31: "Bank Not Supported by Switch",
    33: "Expired Card, Capture",
    34: "Suspected Fraud, Retain Card",
    35: "Card Acceptor, Contact Acquirer, Retain Card",
    36: "Restricted Card, Retain Card",
    37: "Contact Acquirer Security Department, Retain Card",
    38: "PIN Tries Exceeded, Capture",
    39: "No Credit Account",
    40: "Function Not Supported",
    41: "Lost Card",
    42: "No Universal Account",
    43: "Stolen Card",
    44: "No Investment Account",
    51: "Insufficient Funds",
    52: "No Cheque Account",
    53: "No Savings Account",
    54: "Expired Card",
    55: "Incorrect PIN",
    56: "No Card Record",
    57: "Function Not Permitted to Cardholder",
    58: "Function Not Permitted to Terminal",
    59: "Suspected Fraud",
    60: "Acceptor Contact Acquirer",
    61: "Exceeds Withdrawal Limit",
    62: "Restricted Card",
    63: "Security Violation",
    64: "Original Amount Incorrect",
    65: "Exceeds withdrawal",
    66: "Acceptor Contact Acquirer, Security",
    67: "Capture Card",
    75: "PIN Tries Exceeded",
    82: "CVV Validation Error",
    90: "Cutoff In Progress",
    91: "Card Issuer Unavailable",
    92: "Unable To Route Transaction",
    93: "Cannot Complete, Violation Of The Law",
    94: "Duplicate Transaction",
    96: "System Error",
};

export { PosTmsStatusCodes };
